package view;

import Model.Produto;
import controller.ProdutoController;
import java.awt.Color;
import javax.swing.ImageIcon;


public class NovoProduto extends javax.swing.JFrame {
    
    public NovoProduto() {
        initComponents();
        
        this.getContentPane().setBackground(Color.decode("#02153D"));
        String caminhoIcone = "/view/img/ico.png";
        ImageIcon icone = new ImageIcon(getClass().getResource(caminhoIcone));
        this.setIconImage(icone.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNome = new javax.swing.JLabel();
        labelDescricao = new javax.swing.JLabel();
        labelFornecedor = new javax.swing.JLabel();
        jtfFornecedor = new javax.swing.JTextField();
        labelEstoque = new javax.swing.JLabel();
        jtfEstoque = new javax.swing.JTextField();
        labelPreco = new javax.swing.JLabel();
        jtfPreco = new javax.swing.JTextField();
        jbCancelar = new javax.swing.JButton();
        jbConfirmar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jtfNome = new javax.swing.JTextField();
        jtfDescricao = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Novo Produto");
        setResizable(false);

        labelNome.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        labelNome.setForeground(new java.awt.Color(241, 241, 241));
        labelNome.setText("Nome");

        labelDescricao.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        labelDescricao.setForeground(new java.awt.Color(241, 241, 241));
        labelDescricao.setText("Descrição");

        labelFornecedor.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        labelFornecedor.setForeground(new java.awt.Color(241, 241, 241));
        labelFornecedor.setText("Fornecedor");

        jtfFornecedor.setBackground(new java.awt.Color(23, 47, 100));
        jtfFornecedor.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        jtfFornecedor.setForeground(new java.awt.Color(242, 242, 242));
        jtfFornecedor.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));

        labelEstoque.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        labelEstoque.setForeground(new java.awt.Color(241, 241, 241));
        labelEstoque.setText("Estoque");

        jtfEstoque.setBackground(new java.awt.Color(23, 47, 100));
        jtfEstoque.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        jtfEstoque.setForeground(new java.awt.Color(242, 242, 242));
        jtfEstoque.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));

        labelPreco.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        labelPreco.setForeground(new java.awt.Color(241, 241, 241));
        labelPreco.setText("Preço");

        jtfPreco.setBackground(new java.awt.Color(23, 47, 100));
        jtfPreco.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        jtfPreco.setForeground(new java.awt.Color(242, 242, 242));
        jtfPreco.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));

        jbCancelar.setBackground(new java.awt.Color(1, 151, 175));
        jbCancelar.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        jbCancelar.setForeground(new java.awt.Color(255, 255, 255));
        jbCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/icons/xmark.png"))); // NOI18N
        jbCancelar.setText("Cancelar");
        jbCancelar.setBorderPainted(false);
        jbCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbCancelar.setFocusPainted(false);
        jbCancelar.setIconTextGap(10);
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jbConfirmar.setBackground(new java.awt.Color(50, 195, 176));
        jbConfirmar.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        jbConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        jbConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/icons/check.png"))); // NOI18N
        jbConfirmar.setText("Confirmar");
        jbConfirmar.setBorderPainted(false);
        jbConfirmar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbConfirmar.setFocusPainted(false);
        jbConfirmar.setIconTextGap(10);
        jbConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConfirmarActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(23, 47, 100));
        jSeparator1.setForeground(new java.awt.Color(23, 47, 100));
        jSeparator1.setOpaque(true);

        jtfNome.setBackground(new java.awt.Color(23, 47, 100));
        jtfNome.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        jtfNome.setForeground(new java.awt.Color(242, 242, 242));
        jtfNome.setToolTipText("");
        jtfNome.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));

        jtfDescricao.setBackground(new java.awt.Color(23, 47, 100));
        jtfDescricao.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        jtfDescricao.setForeground(new java.awt.Color(242, 242, 242));
        jtfDescricao.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfDescricao)
                    .addComponent(jSeparator1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelEstoque)
                            .addComponent(jtfEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelPreco)
                            .addComponent(jtfPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbConfirmar))
                    .addComponent(labelDescricao)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelNome)
                        .addGap(159, 159, 159)
                        .addComponent(labelFornecedor))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtfFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNome)
                    .addComponent(labelFornecedor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelDescricao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEstoque)
                    .addComponent(labelPreco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCancelar)
                    .addComponent(jbConfirmar))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        this.setVisible(false);
        GerenciaProdutos gp = new GerenciaProdutos();
        gp.setVisible(true);
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jbConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConfirmarActionPerformed
            Produto produto = new Produto();
            
            produto.setNome_produto(this.jtfNome.getText());
            produto.setDescricao_produto(this.jtfDescricao.getText());
            if(this.jtfEstoque.getText().isBlank() || 
                    this.jtfEstoque.getText().isEmpty()) {
                produto.setQuantidade_estoque(Integer.MIN_VALUE);
            } else {
                produto.setQuantidade_estoque(Integer.parseInt(this.jtfEstoque.getText()));
            }
            if(this.jtfPreco.getText().isEmpty() || 
                    this.jtfPreco.getText().isBlank()) {
                produto.setPreco(Float.MIN_VALUE);
            } else { 
                produto.setPreco(Float.parseFloat(this.jtfPreco.getText()));
            }
            produto.setFornecedor(this.jtfFornecedor.getText());
            
            ProdutoController controller = new ProdutoController();
            boolean dadoFoiInserido = controller.inserirNovo(produto);
            
            if(dadoFoiInserido) {
                GerenciaProdutos gProdutos = new GerenciaProdutos();
                gProdutos.atualizarPlanilha();
                setVisible(false);
            }
    }//GEN-LAST:event_jbConfirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NovoProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NovoProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NovoProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NovoProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NovoProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbConfirmar;
    private javax.swing.JTextField jtfDescricao;
    private javax.swing.JTextField jtfEstoque;
    private javax.swing.JTextField jtfFornecedor;
    private javax.swing.JTextField jtfNome;
    private javax.swing.JTextField jtfPreco;
    private javax.swing.JLabel labelDescricao;
    private javax.swing.JLabel labelEstoque;
    private javax.swing.JLabel labelFornecedor;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelPreco;
    // End of variables declaration//GEN-END:variables


}
